---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-sprint-ci
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "1"
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/sprint-cloud/pipelines/main/flask-apps/base/flask-ci-pipeline.yaml"
    pipelinesascode.tekton.dev/task: "git-clone"
    pipelinesascode.tekton.dev/task-1: "pylint"
    pipelinesascode.tekton.dev/task-2: "pytest"
    pipelinesascode.tekton.dev/task-3: "kaniko"
spec:
  podTemplate:
    securityContext:
      fsGroup: 65532
      runAsNonRoot: true
      runAsUser: 1000
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: app-image
      value: "hello-sprint:latest"
  pipelineRef:
    name: flask-ci-pipeline
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: basic-auth
    secret:
      secretName: "{{ git_auth_secret }}"
  - name: dockerconfig
    secret:
      secretName: "dockerconfig"
