---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-sprint-ci
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "1"
spec:
  podTemplate:
    securityContext:
      fsGroup: 65532
      runAsNonRoot: true
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: image
      value: "hello-sprint:latest"
  pipelineRef:
    name: flask-ci-pipeline
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: basic-auth
    secret:
      secretName: "{{ git_auth_secret }}"
  - name: dockerconfig
    secret":
      secretName: "dockerconfig"